version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      # Upgrading to version 5 breaks QR -> HTML parsing, it should be fixed at v4.2.10
      - dependency-name: 'html-react-parser'
      # Should always be fixed at v6.11.2, only this version's useBlocker works with the switching between renderer and renderer/preview without triggering the save dialog to appear
      - dependency-name: 'react-router-dom'
