
FROM node:20 AS build




ARG VITE_ONTOSERVER_URL
ARG VITE_FORMS_SERVER_URL
ARG VITE_LAUNCH_SCOPE
ARG VITE_LAUNCH_CLIENT_ID
ARG VITE_IN_APP_POPULATE
ARG VITE_PRESERVE_SYM_LINKS

ENV VITE_ONTOSERVER_URL $VITE_ONTOSERVER_URL
ENV VITE_FORMS_SERVER_URL $VITE_FORMS_SERVER_URL
ENV VITE_LAUNCH_SCOPE $VITE_LAUNCH_SCOPE
ENV VITE_LAUNCH_CLIENT_ID $VITE_LAUNCH_CLIENT_ID
ENV VITE_IN_APP_POPULATE $VITE_IN_APP_POPULATE
ENV VITE_PRESERVE_SYM_LINKS $VITE_PRESERVE_SYM_LINKS

RUN mkdir /app
COPY . /app
RUN ls /app
WORKDIR /app
RUN npm install
WORKDIR /app/apps/smart-forms-app
