/*
 * Copyright 2023 Commonwealth Scientific and Industrial Research
 * Organisation (CSIRO) ABN 41 687 119 230.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export interface LaunchContext {
  name: string;
  type: FhirResourceString;
}

export type FhirResourceString =
  | 'Account'
  | 'ActivityDefinition'
  | 'AdverseEvent'
  | 'AllergyIntolerance'
  | 'Appointment'
  | 'AppointmentResponse'
  | 'AuditEvent'
  | 'Basic'
  | 'Binary'
  | 'BiologicallyDerivedProduct'
  | 'BodyStructure'
  | 'Bundle'
  | 'CapabilityStatement'
  | 'CarePlan'
  | 'CareTeam'
  | 'CatalogEntry'
  | 'ChargeItem'
  | 'ChargeItemDefinition'
  | 'Claim'
  | 'ClaimResponse'
  | 'ClinicalImpression'
  | 'CodeSystem'
  | 'Communication'
  | 'CommunicationRequest'
  | 'CompartmentDefinition'
  | 'Composition'
  | 'ConceptMap'
  | 'Condition'
  | 'Consent'
  | 'Contract'
  | 'Coverage'
  | 'CoverageEligibilityRequest'
  | 'CoverageEligibilityResponse'
  | 'DetectedIssue'
  | 'Device'
  | 'DeviceDefinition'
  | 'DeviceMetric'
  | 'DeviceRequest'
  | 'DeviceUseStatement'
  | 'DiagnosticReport'
  | 'DocumentManifest'
  | 'DocumentReference'
  | 'EffectEvidenceSynthesis'
  | 'Encounter'
  | 'Endpoint'
  | 'EnrollmentRequest'
  | 'EnrollmentResponse'
  | 'EpisodeOfCare'
  | 'EventDefinition'
  | 'Evidence'
  | 'EvidenceVariable'
  | 'ExampleScenario'
  | 'ExplanationOfBenefit'
  | 'FamilyMemberHistory'
  | 'Flag'
  | 'Goal'
  | 'GraphDefinition'
  | 'Group'
  | 'GuidanceResponse'
  | 'HealthcareService'
  | 'ImagingStudy'
  | 'Immunization'
  | 'ImmunizationEvaluation'
  | 'ImmunizationRecommendation'
  | 'ImplementationGuide'
  | 'InsurancePlan'
  | 'Invoice'
  | 'Library'
  | 'Linkage'
  | 'List'
  | 'Location'
  | 'Measure'
  | 'MeasureReport'
  | 'Media'
  | 'Medication'
  | 'MedicationAdministration'
  | 'MedicationDispense'
  | 'MedicationKnowledge'
  | 'MedicationRequest'
  | 'MedicationStatement'
  | 'MedicinalProduct'
  | 'MedicinalProductAuthorization'
  | 'MedicinalProductContraindication'
  | 'MedicinalProductIndication'
  | 'MedicinalProductIngredient'
  | 'MedicinalProductInteraction'
  | 'MedicinalProductManufactured'
  | 'MedicinalProductPackaged'
  | 'MedicinalProductPharmaceutical'
  | 'MedicinalProductUndesirableEffect'
  | 'MessageDefinition'
  | 'MessageHeader'
  | 'MolecularSequence'
  | 'NamingSystem'
  | 'NutritionOrder'
  | 'Observation'
  | 'ObservationDefinition'
  | 'OperationDefinition'
  | 'OperationOutcome'
  | 'Organization'
  | 'OrganizationAffiliation'
  | 'Parameters'
  | 'Patient'
  | 'PaymentNotice'
  | 'PaymentReconciliation'
  | 'Person'
  | 'PlanDefinition'
  | 'Practitioner'
  | 'PractitionerRole'
  | 'Procedure'
  | 'Provenance'
  | 'Questionnaire'
  | 'QuestionnaireResponse'
  | 'RelatedPerson'
  | 'RequestGroup'
  | 'ResearchDefinition'
  | 'ResearchElementDefinition'
  | 'ResearchStudy'
  | 'ResearchSubject'
  | 'RiskAssessment'
  | 'RiskEvidenceSynthesis'
  | 'Schedule'
  | 'SearchParameter'
  | 'ServiceRequest'
  | 'Slot'
  | 'Specimen'
  | 'SpecimenDefinition'
  | 'StructureDefinition'
  | 'StructureMap'
  | 'Subscription'
  | 'Substance'
  | 'SubstanceNucleicAcid'
  | 'SubstancePolymer'
  | 'SubstanceProtein'
  | 'SubstanceReferenceInformation'
  | 'SubstanceSourceMaterial'
  | 'SubstanceSpecification'
  | 'SupplyDelivery'
  | 'SupplyRequest'
  | 'Task'
  | 'TerminologyCapabilities'
  | 'TestReport'
  | 'TestScript'
  | 'ValueSet'
  | 'VerificationResult'
  | 'VisionPrescription';
