import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  componentsSidebar: [{ type: 'autogenerated', dirName: 'components' }],
  sdcSidebar: [{ type: 'autogenerated', dirName: 'sdc' }],
  devSidebar: [
    { type: 'autogenerated', dirName: 'dev' },
    { type: 'link', label: 'Playground', href: 'https://smartforms.csiro.au/playground' }
  ],
  operationsSidebar: [{ type: 'autogenerated', dirName: 'operations' }],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }]
};

export default sidebars;
