name: Smart Forms Docs Deployment Workflow

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docusaurus:
    name: Deploy Docusaurus to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build documentation website
        run: npm run build -w documentation

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: documentation/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-storybook:
    name: Deploy Storybook to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::209248795938:role/SmartFormsReactAppDeployment
          aws-region: ap-southeast-2

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build-storybook -w packages/smart-forms-renderer

      - name: Upload static Storybook site to S3
        run: aws s3 sync packages/smart-forms-renderer/storybook-static s3://smart-forms-storybook/storybook
