name: Smart Forms Docs + Storybook Deployment Workflow

on:
  push:
    # Only run this workflow when changes are pushed to the main branch
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docusaurus-s3:
    name: Deploy Docusaurus to S3
    runs-on: ubuntu-latest
    # Conditional logic to skip if workflow is triggered by Dependabot
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::209248795938:role/SmartFormsReactAppDeployment
          aws-region: ap-southeast-2

      - name: Install dependencies
        run: npm ci

      - name: Build workspace packages (monorepo dependencies)
        run: |
          npm run build -w packages/sdc-assemble
          npm run build -w packages/sdc-populate
          npm run build -w packages/sdc-template-extract
          npm run build -w packages/smart-forms-renderer

      - name: Build documentation website
        run: npm run build -w documentation

      - name: Upload static Docusaurus site to S3
        run: aws s3 sync documentation/build s3://smart-forms-docs/docs --cache-control no-cache

  deploy-storybook-s3:
    name: Deploy Storybook to S3
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    # Conditional logic to skip if workflow is triggered by Dependabot
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::209248795938:role/SmartFormsReactAppDeployment
          aws-region: ap-southeast-2

      - name: Install dependencies
        run: npm ci

      - name: Build workspace packages (monorepo dependencies)
        run: |
          npm run build -w packages/sdc-assemble
          npm run build -w packages/sdc-populate
          npm run build -w packages/sdc-template-extract

      - name: Build application
        run: npm run build-storybook -w packages/smart-forms-renderer

      - name: Upload static Storybook site to S3
        run: aws s3 sync packages/smart-forms-renderer/storybook-static s3://smart-forms-storybook/storybook
