name: Smart Forms Docs Deployment Workflow

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docusaurus-s3:
    name: Deploy Docusaurus to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::209248795938:role/SmartFormsReactAppDeployment
          aws-region: ap-southeast-2

      - name: Install dependencies
        run: npm ci

      - name: Build documentation website
        run: npm run build -w documentation

      - name: Upload static Docusaurus site to S3
        run: aws s3 sync documentation/build s3://smart-forms-docs/docs --cache-control no-cache
