name: Smart Forms Workflow

on:
  push:
    branches: [ "test-deploy" ]

jobs:
  build:
    name: Deploy to S3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build -w apps/smart-forms-app

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: apps/smart-forms-app/dist
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
