name: Smart Forms Docs Deployment Workflow

on:
  push:
#    branches: [ "main" ]


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v4
#
#      - name: Use Node.js 18.x
#        uses: actions/setup-node@v4
#        with:
#          node-version: 18
#          cache: npm
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Build Storybook
#        run: npm run build-storybook -w packages/smart-forms-renderer

      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: packages/smart-forms-renderer/storybook-static
          install_command: npm ci
          build_command: npm run build-storybook -w packages/smart-forms-renderer
